const academicSkills = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Computer Science Fundamentals',
  'Statistics',
  'Economics',
  'Accounting Basics',
  'Business Studies',
  'History',
  'Geography',
  'Political Science',
  'English Grammar',
  'Essay Writing',
  'Public Exam Preparation',
  'Competitive Exam Aptitude',
  'Reasoning and Logical Thinking',
  'Quantitative Aptitude',
  'Verbal Ability',
  'Language Learning',
  'Spoken English',
  'Hindi Language',
  'French Language',
  'German Language',
  'Spanish Language',
]

const technicalSkills = [
  'Web Development',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'App Development',
  'Android Development',
  'iOS Development',
  'UI/UX Design',
  'Figma Design',
  'Graphic Design',
  'Data Science',
  'Machine Learning',
  'AI Fundamentals',
  'Prompt Engineering',
  'Python Programming',
  'Java Programming',
  'C++ Programming',
  'JavaScript Programming',
  'TypeScript Programming',
  'React Development',
  'Node.js Development',
  'Express.js Development',
  'MongoDB',
  'SQL Databases',
  'System Design Basics',
  'Data Structures and Algorithms',
  'DevOps Basics',
  'Git and GitHub',
  'Cloud Fundamentals',
  'Cybersecurity Basics',
]

const extracurricularSkills = [
  'Guitar',
  'Piano',
  'Singing',
  'Music Production Basics',
  'Public Speaking',
  'Debate',
  'Storytelling',
  'Chess',
  'Art and Sketching',
  'Digital Illustration',
  'Photography',
  'Photo Editing',
  'Video Editing',
  'Content Creation',
  'Fitness and Workout Basics',
  'Yoga',
  'Meditation and Mindfulness',
  'Dance Basics',
  'Theatre and Acting',
  'Creative Writing',
  'Resume Building',
  'Interview Preparation',
  'Leadership Skills',
  'Teamwork and Collaboration',
  'Time Management',
]

module.exports = {
  academicSkills,
  technicalSkills,
  extracurricularSkills,
}
