const FIXED_CREDIT_PRICE = 10
const MIN_COMPLETION_RATIO = 0.75
const BYPASS_COMPLETION_DURATION_CHECK =
  String(process.env.BYPASS_COMPLETION_DURATION_CHECK || '').trim().toLowerCase() === 'true'

module.exports = {
  FIXED_CREDIT_PRICE,
  MIN_COMPLETION_RATIO,
  BYPASS_COMPLETION_DURATION_CHECK,
}
